# Generated by Django 4.2.6 on 2023-10-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
