# Generated by Django 4.2.6 on 2023-10-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contact_contact_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
